                  ##########
                  ##README##
                  ##########
# True and False values MUST be capitalized
# All option settings are CASE SENSITIVE. EX 'VB6' not 'vb6' or 'Vb6'

#To install this software to run automatically on the controller, follow below:
#   1.  Create a 'salesgen' folder on the C: drive
#   2.  Copy the executable and .yaml config file to the salesgen folder
#   3.  Configure the .yaml document to the necessary specs
#   4.  Open Windows Task Scheduler
#   5.  On the right side of Task Scheduler, click 'Create Basic Task'
#   6.  For name enter in salesgen
#   7.  For task trigger select 'Daily'
#   8.  Set the start time to 1am and have it recur daily
#   9.  Select 'Start a Program'
#   10. Select the salesgen .exe for 'Program/script'
#   11. Enter '-h' in 'Add arguments'
#   12. Enter the path to the salesgen folder for 'Start in'
#   13. Press 'Finish'


#SOFTWARE_VERSION CAN BE EITHER "VB6" OR ".NET"
SOFTWARE_VERSION: ".NET"

#Site ID/Site number override
site_number: "1234"

ptOutput: False #CFN PT output
gasboyOutput: False #Gasboy log printer output
csvOutput: True #CSV output
CFNcsv:    False
merchantAg: False #Merchant Agriculture output (EFC)
VDPOutput: False #Van De Pol specific output
AGTRAX: False
JCDoyle: False
FuelMaster: False
HuntBreshers: False

#COMPANY LIST. ENABLE THESE FOR COMPANY SPECIFIC OUTPUT MODIFICATIONS
Downs: False
Busch: False
Acme: False
Dawson: False

#DAILY and ALL options are available for pullMode
pullMode: "ALL"

#Outputs multiple files based on date and time.
#This requires the date to be in the file name
individual_files: True

#Selects specific VB6 sales files. 
#EX: .p1c = 'p', .d1c = 'd', or for both 'pd'
processors_VB6: ""

#Input and output folder paths. There can be multiple input locations if you'd like.
input_folders: 
  - 
output_folder: 

# What will be included in the PT file name
file_name: 
  #Sets the beginning of the file
  custom: 
    custom_beginning: True
    text: "Test"
  #Adds the site id to the file name. Pulls from the file or the site_number override
  siteid: False
  #Filename date options
  date:
    include: True
    format: False # Date formatting. True = yymmdd False = mmddyy
    add_day: True # Adds day to date. Only used on Anaheim Truck Depot sites
  extension: ".csv"

USE_FTP: True
FTP_Settings:
  Username: 
  Password: 
  HostName: 
  Destination: /example
  USE_TLS: False

USE_SFTP: False
SFTP_Settings:
  Username:
  Password:
  HostName:
  #SSH key goes here. Required in order to cleanly connect with this implementation
  KeyData: 

USE_EMAIL: False
EMAIL_Settings:
  mailServer: smtp.office365.com
  mailPort: 587
  mailUser: 
  mailPassword: 
  messageSubject:
  messageBody: 
  to:
    - example@example.net
   #- anotherExample@example.net



