                  ##########
                  ##README##
                  ##########
# True and False values MUST be capitalized
# File paths must not have \\ at the end

#SOFTWARE_VERSION CAN BE EITHER "VB6" OR ".NET"
SOFTWARE_VERSION: ".NET"

site_number: ""

ptOutput: False #CFN PT output
gasboyOutput: False #Gasboy log printer output
csvOutput: False #CSV output
CFNcsv:    False
merchantAg: False #Merchant Agriculture output (EFC)
VDPOutput: False #Van De Pol specific output
AGTRAX: False
JCDoyle: False
FuelMaster: False
HuntBreshers: False

#COMPANY LIST. ENABLE THESE FOR COMPANY SPECIFIC OUTPUT MODIFICATIONS
Downs: False
Busch: False
Atlas: False
Dawson: False

#DAILY and ALL options are available for pullMode
pullMode: "ALL"

# Path where PT file will get output
# MUST USE DOUBLE BACKSLASHES
# EX: "C:\\ICS\\YOUR FOLDER HERE\\ANOTHER FOLDER"
input_folders: 
  - C:\SalesGen\.Net\AGTRAX\input
output_folder: C:\SalesGen\.Net\AGTRAX\output

file_name: # What will be included in the PT file name
  custom: # Allows for custom file name beginning if wanted
    custom_beginning: True
    text: "AGTRAX_NEWSOFTWARE"
  siteid: False
  date:
    include: False
    format: False # Date formatting. True = yymmdd False = mmddyy
    add_day: False # Adds day to date. Only used on Anaheim Truck Depot sites
  extension: ".DDF"

USE_SFTP: False
SFTP_Settings:
  Username:
  Password:
  HostName:
  KeyData:

USE_EMAIL: False
EMAIL_Settings:
  mailServer:
  mailPort:
  mailUser:
  mailPassword:
  messageSubject:
  messageBody:
  to:
    -"example@example.com"
   #-"more in list"



